### ISSUE TITLE
One-step-ahead residuals for LFOIC

### ISSUE THREAD

**Issue by rwildermuth** [futureseas/recrmntDFA#1]
For calculating the root mean squared error of MARSS residuals for recruitment deviation time series in the [leave-future-out information criterion](https://github.com/futureseas/recrmntDFA/blob/main/R/LFOXV.R), we need to make sure we're calculating the residual between the input recdev value at the last time (tmax) for a cross validation peel and the expected value of that datum _without_ knowing the observed value. In the residuals.marssMLE() help file there are three types of standard residuals:

Smoothation residual (tT): residual conditioned on all data to time T = tmax
Innovation residual (tt1): residual conditioned on data from time 1 to t-1
Contemporaneous residual (tt): residual conditioned on data from time 1 to t (also tmax?)

Right now I've changed the function to calculate RMSE based on innovation residuals, but this means the full set of indicators only up to t-1. This is slightly different from what the climate projections will use, which is similar to contemporaneous residuals, but with missing data for the variables of interest (recdevs). I'm not sure there's a way to calculate a residual conditioned on only projection data from time 1 to t with a variable of interest left out at time t (something like a "concomitant residual"?).

@detommas, do you think the Innovation residual will work for the LFOXV for now?

**Comment by detommas** [comment]
I agree that the innovation residuals are the closest to what we want, but so we and other folks looking at the code are clear as to what is being done, I think we should calculate the residuals explicitly in the code as the difference between the observed and the predicted, only over those years we are "leaving out". I would instead fit the model with the specified peel, and then predict using predict(ytT, newdat = all the ys except the var of interest for the peeled out year). According to the predict.marssMLE help this way the predictions are computed using newdata but with the MARSS model estimated from the original data.

**Comment by rwildermuth** [comment]
I updated the LFOXV function to include comparisons of residual formulations. Currently the function reports the LFOIC calculated with an informed innovation residual aggregated over peels and variables of interest.

@detommas take a look and let me know if any changes are needed.

**Comment by rwildermuth** [comment]
Integrated Desiree's edits into [OSAResids() ](https://github.com/futureseas/recrmntDFA/blob/main/R/OSAResids.R) to make sure tested data for one-step-ahead residuals aren't included in model fit of the peel.
